---
# SolukOS Linux icin bootloader (GRUB) yapilandirmasi.
# Kaynak: BlackArch'in gercek, calisan Calamares yapilandirmasi
# (github.com/BlackArch/blackarch-config-calamares) - gercek bir
# Arch-tabanli dagitimdan birebir uyarlandi, sadece giris ismi degisti.

efiBootLoader: "grub"
# systemd-boot

kernelSearchPath: "/usr/lib/modules"
kernelName: "vmlinuz-linux"
timeout: "10"
additionalInitrdFiles:
    - "/boot/amd-ucode.img"
    - "/boot/intel-ucode.img"

bootloaderEntryName: "SolukOS Linux"

# Grub

grubInstall: "grub-install"
grubMkconfig: "grub-mkconfig"
grubCfg: "/boot/grub/grub.cfg"
grubProbe: "grub-probe"
efiBootMgr: "efibootmgr"
installEFIFallback: true
