---
showSupportUrl: true
showKnownIssuesUrl: false
showReleaseNotesUrl: false
showDonateUrl: false

requirements:
    requiredStorage: 8.0
    requiredRam: 2.0
    check: [ storage, ram, power ]
    required: [ storage ]
