background             #0a0e0a
foreground             #33ff66
cursor                 #33ff66
selection_background   #123018
selection_foreground   #33ff66
color0                 #0a0e0a
color8                 #123018
color1                 #1f7a3f
color9                 #1f7a3f
color2                 #33cc55
color10                #33cc55
color3                 #5ee87a
color11                #5ee87a
color4                 #268a4a
color12                #268a4a
color5                 #2fb35c
color13                #2fb35c
color6                 #39d466
color14                #39d466
color7                 #a8f7bb
color15                #a8f7bb
