# SolukOS Ana Yapılandırma Dosyası
OS_NAME="SolukOS"
OS_VERSION="2026.1-RELEASE"
ARCH="x86_64"
WORK_DIR="/tmp/solukos_build"
ISO_NAME="SolukOS-2026.1-x86_64.iso"

# Debug & Kurtarma Ayarları
SYSTEMD_SULOGIN_FORCE=1
ENABLE_DEBUG_SHELL=true
LOG_LEVEL="debug"
