[Appearance]
style=Fusion
standard_dialogs=default
icon_theme=Papirus-Dark

[Fonts]
general="Noto Sans,10,-1,5,400,0,0,0,0,0,0,0,0,0,0,1"
fixed="JetBrainsMono Nerd Font,10,-1,5,400,0,0,0,0,0,0,0,0,0,0,1"
