[Desktop]
WallpaperMode=zoom
Wallpaper=/usr/share/wallpapers/SolukOS/contents/images/2560x1440.png
BgColor=#1c1f24
FgColor=#c0c8d0
ShadowColor=#000000
ShowHidden=false
SortOrder=ascending
SortColumn=name
