background {
    monitor =
    path = /usr/share/wallpapers/SolukOS/contents/images/2560x1440.png
    blur_passes = 2
    blur_size = 7
    contrast = 0.9
    brightness = 0.75
    vibrancy = 0.15
}

input-field {
    monitor =
    size = 250, 50
    outline_thickness = 2
    dots_size = 0.3
    dots_spacing = 0.2
    outer_color = rgba(127, 159, 191, 1.0)
    inner_color = rgba(28, 31, 36, 0.85)
    font_color = rgba(192, 200, 208, 1.0)
    fade_on_empty = true
    placeholder_text = Parola
    hide_input = false
    position = 0, -60
    halign = center
    valign = center
}

label {
    monitor =
    text = SolukOS
    color = rgba(192, 200, 208, 1.0)
    font_size = 28
    font_family = Noto Sans
    position = 0, 60
    halign = center
    valign = center
}

label {
    monitor =
    text = $TIME
    color = rgba(127, 159, 191, 1.0)
    font_size = 56
    font_family = Noto Sans
    position = 0, 140
    halign = center
    valign = center
}

image {
    monitor =
    path = /etc/calamares/branding/solukos/logo.png
    size = 100
    rounding = -1
    border_size = 0
    position = 0, 240
    halign = center
    valign = center
}
