# SolukOS Hyprlock

# Fallback renkler
$solukos_bg         = rgba(1c1f24ee)
$solukos_bg_solid   = rgba(1c1f24ff)
$solukos_accent     = rgba(7f9fbfee)
$solukos_text       = rgba(c0c8d0ff)

source = $HOME/.config/soluk/themes/solukos/hypr-theme.conf

background {
    monitor =
    path = /usr/share/wallpapers/SolukOS/contents/images/2560x1440.png
    blur_passes = 2
    blur_size = 7
    contrast = 0.9
    brightness = 0.75
    vibrancy = 0.15
}

input-field {
    monitor =
    size = 250, 50
    outline_thickness = 2
    dots_size = 0.3
    dots_spacing = 0.2
    outer_color = $solukos_accent
    inner_color = $solukos_bg
    font_color = $solukos_text
    fade_on_empty = true
    placeholder_text = Parola
    hide_input = false
    position = 0, -60
    halign = center
    valign = center
}

label {
    monitor =
    text = SolukOS
    color = $solukos_text
    font_size = 28
    font_family = Noto Sans
    position = 0, 60
    halign = center
    valign = center
}

label {
    monitor =
    text = $TIME
    color = $solukos_accent
    font_size = 56
    font_family = Noto Sans
    position = 0, 140
    halign = center
    valign = center
}

image {
    monitor =
    path = /etc/calamares/branding/solukos/logo.png
    size = 100
    rounding = -1
    border_size = 0
    position = 0, 240
    halign = center
    valign = center
}
